name: Test Node.js Express Install

on: push
  #workflow_dispatch:

jobs:
  test-node:
    runs-on: [self-hosted, linux]  # ë“±ë¡í•œ ëŸ¬ë„ˆ ë¼ë²¨ë¡œ ìˆ˜ì •
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setting Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check node & npm version
        run: node -v && npm -v

      - name: Install dependencies
        run: npm install express https ws

      - name: Test require
        run: node -e "require('express'); require('https'); require('ws'); console.log('ëª¨ë“ˆ ì •ìƒ ì„¤ì¹˜ í™•ì¸!')"

  Explore-GitHub-Actions:
    runs-on: [self-hosted, linux]
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
